name: demographic-modeling

channels:
  - esri
  - conda-forge
  - knu2xs

dependencies:
  - anaconda
  - arcgis==1.8.2
  - cookiecutter
  - ba-tools
  - bump2version
  - dask
  - h3-py
  - jupyterlab
  - mkdocs
  - pip
  - pylint
  - pytest
  - python-dotenv
  - pyyaml
  - scipy
  - scikit-learn
  - shapely
  - swifter
  - tqdm
  - pip:
    - ipykernel
    - pyarrow
    - sphinx
    - sphinx-autodoc-typehints
    - sphinx_rtd_theme
    - twine